"""update class item

Revision ID: 83a4ebaf51b1
Revises: f6c3e60df7d7
Create Date: 2023-11-14 17:06:29.116713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a4ebaf51b1'
down_revision = 'f6c3e60df7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_store_id_bakery', type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_items_store_id_bakery', 'bakery', ['store_id'], ['id'])

    # ### end Alembic commands ###
