"""empty message

Revision ID: 852a82eec3b7
Revises: 83a4ebaf51b1
Create Date: 2023-11-16 21:53:33.836212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852a82eec3b7'
down_revision = '83a4ebaf51b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
