"""update class item

Revision ID: f6c3e60df7d7
Revises: b9b2ec3df0c2
Create Date: 2023-11-14 17:03:34.819866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c3e60df7d7'
down_revision = 'b9b2ec3df0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_items_store_id_bakery'), 'bakery', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_store_id_bakery'), type_='foreignkey')

    # ### end Alembic commands ###
